"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Loader2, FileText, Zap, BookOpen, GraduationCap, Copy, Check } from "lucide-react";
import { useLearningContent } from "@/hooks/use-learning-content";

type SummaryType = "short" | "detailed" | "key_concepts" | "exam";

const types: { id: SummaryType; label: string; icon: any; description: string }[] = [
  { id: "short", label: "Brief Overview", icon: Zap, description: "A quick summary of the core topics." },
  { id: "detailed", label: "Deep Dive", icon: BookOpen, description: "Highly detailed breakdown of all knowledge." },
  { id: "key_concepts", label: "Key Concepts", icon: FileText, description: "Focus on the most important definitions." },
  { id: "exam", label: "Exam Focus", icon: GraduationCap, description: "Condensed points tailored for test prep." },
];

export function SummarizeInterface({ buddyId }: { buddyId: string }) {
  const [selectedType, setSelectedType] = useState<SummaryType>("short");
  const [copied, setCopied] = useState(false);
  const { summaries } = useLearningContent(buddyId);

  // Get the most recent summary of the selected type
  const currentSummary = summaries.data.find((s: any) => s.type === selectedType);

  const generateSummary = async () => {
    try {
      await summaries.generate.mutateAsync(selectedType);
    } catch (error) {
      console.error("Summarize error:", error);
      alert("Failed to generate summary. Make sure you have uploaded documents.");
    }
  };

  const copyToClipboard = () => {
    if (!currentSummary) return;
    navigator.clipboard.writeText(currentSummary.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      <div className="text-center space-y-2">
        <h2 className="text-3xl font-black text-slate-900 tracking-tight">AI Knowledge Summarizer</h2>
        <p className="text-slate-500 font-medium">Select a focus mode to condense your study material.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {types.map((type) => (
          <button
            key={type.id}
            onClick={() => setSelectedType(type.id)}
            className={`
              flex flex-col items-center p-6 rounded-3xl border-2 transition-all duration-300 text-center
              ${selectedType === type.id 
                ? "bg-primary/5 border-primary shadow-lg shadow-primary/10 ring-4 ring-primary/5" 
                : "bg-white border-slate-100 hover:border-slate-200 hover:bg-slate-50"}
            `}
          >
            <div className={`p-3 rounded-2xl mb-4 ${selectedType === type.id ? "bg-primary text-white" : "bg-slate-100 text-slate-400"}`}>
               <type.icon className="w-6 h-6" />
            </div>
            <h3 className={`font-bold mb-1 ${selectedType === type.id ? "text-primary" : "text-slate-900"}`}>{type.label}</h3>
            <p className="text-[10px] uppercase font-black tracking-widest text-slate-400">{type.description}</p>
          </button>
        ))}
      </div>

      <div className="flex justify-center">
        <Button 
          size="lg" 
          onClick={generateSummary} 
          disabled={summaries.isLoading || summaries.generate.isPending}
          className="rounded-full px-12 py-8 text-xl font-black shadow-xl shadow-primary/20 hover:scale-105 active:scale-95 transition-all"
        >
          {summaries.generate.isPending ? <Loader2 className="w-6 h-6 animate-spin mr-3" /> : <Zap className="w-6 h-6 mr-3" />}
          {currentSummary ? "Regenerate Summary" : "Generate Summary"}
        </Button>
      </div>

      {currentSummary && (
        <Card className="bg-white border-slate-200 shadow-2xl overflow-hidden animate-in fade-in slide-in-from-bottom-8 duration-700">
          <CardHeader className="bg-slate-50/50 border-b border-slate-100 flex flex-row items-center justify-between">
            <div>
              <CardTitle className="text-xl font-black text-slate-900">Research Notes</CardTitle>
              <CardDescription className="font-bold text-primary uppercase text-[10px] tracking-widest mt-1">Generated by MyBuddy AI</CardDescription>
            </div>
            <Button variant="ghost" size="sm" onClick={copyToClipboard} className="text-slate-400 hover:text-primary rounded-xl font-bold">
               {copied ? <Check className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
               {copied ? "Copied!" : "Copy Text"}
            </Button>
          </CardHeader>
          <CardContent className="p-8">
            <div className="prose prose-slate max-w-none">
               <div className="whitespace-pre-wrap text-slate-700 leading-relaxed font-medium">
                  {currentSummary.content}
               </div>
            </div>
          </CardContent>
        </Card>
      )}

      {summaries.generate.isPending && (
        <div className="flex flex-col items-center justify-center py-20 animate-pulse text-center">
           <div className="w-16 h-16 rounded-3xl bg-slate-100 mb-6 flex items-center justify-center">
              <Loader2 className="w-8 h-8 animate-spin text-slate-300" />
           </div>
           <h3 className="text-xl font-black text-slate-400">Processing Knowledge...</h3>
           <p className="text-slate-400 font-medium">This usually takes about 10-15 seconds.</p>
        </div>
      )}
    </div>
  );
}
